version: "3.7"
services:
  mongodb:
    image: mongo:latest
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: local_dev
      MONGO_INITDB_ROOT_PASSWORD: local_dev


  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
    environment:
      - DB_HOST=mongodb
      - DB_USER=local_dev
      - DB_PASSWORD=local_dev
      - DB_NAME=local_dev
      - DB_PORT=27017

    command: npm run dev

  frontend:
    build:
      context: ./frontend
      target: build-stage
      args:
        - DEV=true

    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: ng serve --host 0.0.0.0 --port 3000 --disable-host-check