version: "3.7"
services:
  mongodb:
    image: mongo:latest
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: local_dev
      MONGO_INITDB_ROOT_PASSWORD: local_dev


  backend:
    build: ./backend
    image: lijen0317/backend:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
    environment:
      - DB_HOST=mongodb
      - DB_USER=local_dev
      - DB_PASSWORD=local_dev
      - DB_NAME=local_dev
      - DB_PORT=27017

    command: npm run dev

  frontend:
    build:
      context: ./frontend
      target: runtime-stage
      args:
        - DEV=false

    image: lijen0317/frontend:latest
    ports:
      - "80:80"
    command: ["nginx", "-g", "daemon off;"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1  # Use the version compatible with your Kibana
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  # Adjust the Java heap sizes as per your requirement
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.1  # Use the version that matches the Elasticsearch version
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
volumes:
  esdata: # This volume is used for storing Elasticsearch data