version: "3.7"
services:
  mongodb:
    image: mongo:latest
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: local_dev
      MONGO_INITDB_ROOT_PASSWORD: local_dev


  backend:
    build: ./backend
    image: lijen0317/backend:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
    environment:
      - DB_HOST=mongodb
      - DB_USER=local_dev
      - DB_PASSWORD=local_dev
      - DB_NAME=local_dev
      - DB_PORT=27017

    command: /bin/bash -c "npm run build &&
                            npm start"

  frontend:
    build:
      context: ./frontend
      target: runtime-stage
      args:
        - DEV=false

    image: lijen0317/frontend:latest
    ports:
      - "80:80"
    command: ["nginx", "-g", "daemon off;"]